spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbquery?serverTimezone=UTC
    username: root2
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:changelog.xml